compressionLevel: mixed

nodeLinker: node-modules

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs

npmScopes:
  clinia:
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN-}
